force-app/main/default/objects/School_Object__c/School_Object__c.object-meta.xml
<CustomObject>
    <description>The &quot;School Object&quot; is a custom object in Salesforce that serves to store and manage specific data related to educational institutions associated with the company&apos;s operations. It may include fields such as School Name, School ID, Location, Contact Information, Associated Programs, Number of Students, and other relevant details. This object is used to track, report, and analyze interactions between the company and the schools, facilitating effective relationship management.</description>
    <label>School Object</label>
    <nameField>
        <label>School Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Object__c/fields/Billing_Version__c.field-meta.xml
<CustomField>
    <fullName>Billing_Version__c</fullName>
    <description>Indicates if the school is on billing V1 or V2 or V3</description>
    <inlineHelpText>Indicates if the school is on billing V1 or V2 or V3</inlineHelpText>
    <label>Billing Version</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School_Object__c/fields/Brightwheel_School_UUID__c.field-meta.xml
<CustomField>
    <fullName>Brightwheel_School_UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Brightwheel School UUID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SchoolObjectTriggerTest.cls
@isTest
private class SchoolObjectTriggerTest {
@IsTest
    Static void test_SchoolObjectTrigger(){
        School_Object__c school = new School_Object__c(
            Name = 'test',
            Brightwheel_School_UUID__c = '***********'
        );

        insert school;

        school.Billing_Version__c  = 'test';
        update school;
        
        delete school;
        undelete school;        
    }
    
}