force-app/main/default/objects/Onboarding_Attempt__c/Onboarding_Attempt__c.object-meta.xml
<CustomObject>
    <description>It is essential for the business to be able to track current and historical Onboarding attempts on an account for a variety of reasons: KPIs, goals, success rate of each Onboarding attempt, YoY/MoM activation rates etc. When an account becomes a customer, a new SaaS and/or Billing Onboarding Attempt(s) is created. Once the attempt is Closed or Canceled (or any other closed status), the Attempt locks down and no future changes will be made to it.</description>
    <label>Onboarding Attempt</label>
    <nameField>
        <label>Onboarding Attempt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Attempts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Attempt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboarding Attempts</relationshipLabel>
    <relationshipName>Onboarding_Attempts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Onboarding_Attempt__c/fields/Brightwheel_School_UUID_Stamp__c.field-meta.xml
<CustomField>
    <fullName>Brightwheel_School_UUID_Stamp__c</fullName>
    <label>Brightwheel School UUID - Stamp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OnboardingAttemptTriggerTest.cls
@isTest
public class OnboardingAttemptTriggerTest {
@IsTest
    Static void test_CombinedFunnelTrigger(){
        Account acct = new Account(
            Name = 'test'
        );

        insert acct;

        Onboarding_Attempt__c OA = new Onboarding_Attempt__c(
            Account__c = acct.id
            
        );
        
        insert OA;
        
        OA.Brightwheel_School_UUID_Stamp__c  = '********';
        update OA;
        
        delete OA;
        undelete OA;        
    }
    
}