force-app/main/default/objects/Generic_Email_Domain__c/Generic_Email_Domain__c.object-meta.xml
<CustomObject>
    <label>Generic Email Domain</label>
    <nameField>
        <displayFormat>GEN-{0000}</displayFormat>
        <label>Generic Email Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generic Email Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Generic_Email_Domain__c/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <label>Email Domain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <description>Custom object used for connecting external TAM/TED database data with Leads and Contact data.</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Outbound_Email__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Email__c</fullName>
    <description>Sourced email address for the school primary contact.</description>
    <externalId>true</externalId>
    <inlineHelpText>Sourced email address for the school primary contact.</inlineHelpText>
    <label>Organization Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/OrgTrigTest.cls
@isTEst
private class OrgTrigTest {
 
  static testmethod void insertOrgandEmail() {
    // Create lead
    
    Generic_Email_Domain__c GED = new Generic_Email_Domain__c();
    GED.Email_Domain__c = 'hotmail.com';
    insert GED;
      
    Organization__c o = new Organization__c();
    //o.Company = 'Williams Inc';
    o.Outbound_Email__c = 'dylanwilliams@hotmail.com';
    insert o;

    o.Outbound_Email__c = 'dylanwilliams2@hotmail.com';
    update o;

    delete o;
  }
}