force-app/main/default/objects/Area_code__c/Area_code__c.object-meta.xml
<CustomObject>
    <description>Area code to state and state code</description>
    <label>Area code</label>
    <nameField>
        <label>Area code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Area_code__c/fields/State_abbreviation__c.field-meta.xml
<CustomField>
    <fullName>State_abbreviation__c</fullName>
    <label>State abbreviation</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/School_Object__c/School_Object__c.object-meta.xml
<CustomObject>
    <description>The &quot;School Object&quot; is a custom object in Salesforce that serves to store and manage specific data related to educational institutions associated with the company&apos;s operations. It may include fields such as School Name, School ID, Location, Contact Information, Associated Programs, Number of Students, and other relevant details. This object is used to track, report, and analyze interactions between the company and the schools, facilitating effective relationship management.</description>
    <label>School Object</label>
    <nameField>
        <label>School Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>School Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/School_Object__c/fields/Brightwheel_School_UUID__c.field-meta.xml
<CustomField>
    <fullName>Brightwheel_School_UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Brightwheel School UUID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/School_Object__c/fields/Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Owner_Email__c</fullName>
    <label>Owner email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/AreaCodeLookupTest.cls
@isTest
private class AreaCodeLookupTest {

		static testmethod void insertLeadwithphone() {
		//Create school
		School_Object__c s = new School_Object__c();
		s.Account_Name__c = 'Dylan School';
        s.Owner_Email__c = 'test@test.com';
		s.Brightwheel_School_UUID__c = '123a';
		insert s;

		//Craete area code
		Area_code__c a = new Area_code__c();
		a.Name = '717';
		a.State_abbreviation__c = 'PA';
		insert a;

		// Create lead
		Lead l = new Lead();
		l.LastName = 'Williams';
		l.FirstName = 'Test';
		l.Company = 'Williams Inc';
		l.Email = 'dylanwilliams@mybrightwheel.com';
		l.Phone = '+1(717) 555-5555';
		l.School_object__c = s.id;
		insert l;

        Lead l2 = new Lead();
		l2.LastName = 'Williams';
		l2.FirstName = 'Test';
		l2.Company = 'Williams Inc.';
		l2.Email = 'dylanwilliams1@mybrightwheel.com';
		l2.Phone = '(717) 555-5556';
		l2.School_object__c = s.id;
		insert l2;

	}

}