force-app/main/default/objects/Combined_Funnel__c/Combined_Funnel__c.object-meta.xml
<CustomObject>
    <description>Used to track combined SaaS and Billing onboarding/activation funnels for an Account.</description>
    <label>Combined Funnel</label>
    <nameField>
        <label>Combined Funnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Combined Funnels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Combined_Funnel__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Combined Funnels</relationshipLabel>
    <relationshipName>Combined_Funnels</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Combined_Funnel__c/fields/Billing_Status_at_CW__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status_at_CW__c</fullName>
    <description>Captured on CW SaaS Opp by ISR&apos;s. Mapped to Combined Funnel record on CW.</description>
    <inlineHelpText>Populated from the SaaS CW Opportunity</inlineHelpText>
    <label>Billing Status at CW</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Status_at_CW</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Combined_Funnel__c/fields/Onboarding_Path__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Path__c</fullName>
    <description>Mapped from CW Opp.</description>
    <label>Onboarding Path</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Onboarding_Path</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Billing_Status_at_CW.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Opted In</fullName>
    </customValue>
    <customValue>
        <fullName>Soft Opt Out</fullName>
    </customValue>
    <customValue>
        <fullName>Hard Opt Out</fullName>
    </customValue>
    <customValue>
        <fullName>Not for Sales - Cancelled SaaS</fullName>
    </customValue>
    <customValue>
        <fullName>Passed to Upsell</fullName>
        <isActive>false</isActive>
        <label>Passed to Upsell</label>
    </customValue>
    <customValue>
        <fullName>Closed Won During Demo</fullName>
        <isActive>false</isActive>
        <label>Closed Won During Demo</label>
    </customValue>
    <customValue>
        <fullName>Opted Out</fullName>
        <isActive>false</isActive>
        <label>Opted Out</label>
    </customValue>
    <masterLabel>Billing Status at CW</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CombinedFunnelTriggerTest.cls
@isTest
public class CombinedFunnelTriggerTest {
@IsTest
    Static void test_CombinedFunnelTrigger(){
        Account acct = new Account(
            Name = 'test'
        );

        insert acct;

        Combined_Funnel__c CF = new Combined_Funnel__c(
            Account__c = acct.id,
            Billing_Status_at_CW__c = 'Opted In',
            Onboarding_Path__c = 'Combined'
            
        );
        
        insert CF;
        
        CF.Onboarding_Path__c = 'Standard';
        update CF;
        
        delete CF;
        undelete CF;        
    }
    
}