force-app/main/default/objects/Onboarding__c/Onboarding__c.object-meta.xml
<CustomObject>
    <label>Onboarding</label>
    <nameField>
        <label>Onboarding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboardings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboardings</relationshipLabel>
    <relationshipName>Onboardings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Onboarding__c/fields/Multi_Site__c.field-meta.xml
<CustomField>
    <fullName>Multi_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captured by sales on closed-won Opp.</description>
    <inlineHelpText>Is the center a multi-site?</inlineHelpText>
    <label>Multi-Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OnboardingTriggerTest.cls
@isTest
public class OnboardingTriggerTest {

@IsTest
    Static void test_AccountTrigger(){
        Account acct = new Account(
            Name = 'test'
        );

        insert acct;

        Onboarding__c OB = new Onboarding__c(
            Account__c = acct.id,
            Multi_Site__c = FALSE
        );
        
        insert OB;
        
        OB.Multi_Site__c = TRUE;
        update OB;
        
        delete OB;
        undelete OB;        
    }
}