force-app/main/default/objects/Contact_Center_Agent_Preference__c/Contact_Center_Agent_Preference__c.object-meta.xml
<CustomObject>
    <label>Contact Center Agent Preference</label>
    <nameField>
        <label>Contact Center Agent Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Center Agent Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Center_Agent_Preference__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Center_Agent_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Center_Agent_Preference__c/fields/Agent_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Agent_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>Agent User Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact_Center_Agent_Preference__c/fields/Apply_Local_Presence__c.field-meta.xml
<CustomField>
    <fullName>Apply_Local_Presence__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This fields calls from the local presence number if it set to true for that particular agent.</description>
    <label>Apply Local Presence</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Center_Agent_Preference__c/fields/Contact_Center_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Center_Number__c</fullName>
    <label>Contact Center Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AgentOutboundNumberPreferenceService.cls
public class AgentOutboundNumberPreferenceService {
    @AuraEnabled
    public static Boolean saveSelectedOutboundNumber(String selectedNumber) {
        try { 
            Id currentUserId = UserInfo.getUserId();
            Boolean localPresenceSelected = false;
            if(selectedNumber == 'OWN'){
                localPresenceSelected = false;
            }else if(selectedNumber == 'LOCAL_PRESENCE'){
                localPresenceSelected = true;
            }

            Contact_Center_Agent_Preference__c pref = new Contact_Center_Agent_Preference__c(
                Agent__c = currentUserId,
                Agent_User_Id__c = currentUserId,
                Apply_Local_Presence__c = localPresenceSelected
                //Selected_Number__c = selectedNumber
            );
            
            upsert pref Agent_User_Id__c;
            
            return true;
            
        } catch (Exception e) {
            System.debug('Error updating agent preference');
            System.debug(e.getMessage());
            return false;
        }
    }
    
    @AuraEnabled
    public static Contact_Center_Agent_Preference__c getAgentCallCenterNumber(){
        try{
            Id currentuserId = UserInfo.getUserId();
            Contact_Center_Agent_Preference__c u = [SELECT Id, Contact_Center_Number__c , Apply_Local_Presence__c FROM Contact_Center_Agent_Preference__c WHERE Agent__c = :currentUserId LIMIT 1];
            if (u == null) {
                return null;
            }
            return u;
        }catch(Exception e){
            return null;
        }
        
        
    }
}