force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <description>Custom object used for connecting external TAM/TED database data with Leads and Contact data.</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/LOGIC_Apex_counter__c.field-meta.xml
<CustomField>
    <fullName>LOGIC_Apex_counter__c</fullName>
    <description>Field for Apex sweeper to update to trigger process builders</description>
    <label>LOGIC Apex counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactSweep.cls
global class ContactSweep implements Database.Batchable<sObject> {

     // Start QueryLocator
     global Database.QueryLocator start(Database.BatchableContext BC) {

     String query = 'SELECT id, LOGIC_Apex_counter__c ' +
                    'FROM Contact ' +
                    'WHERE Organization__c = null';

     return Database.getQueryLocator(query);
    }

    // Execute processing each batch of records
    global void execute(Database.BatchableContext BC, List<Contact> activecon) {
    // system.debug('>>> listBL ' + activelead);

        for(Contact c : activecon){
            if(c.LOGIC_Apex_counter__c == null) {
               c.LOGIC_Apex_counter__c = 1;
               } else {
               c.LOGIC_Apex_counter__c = c.LOGIC_Apex_counter__c + 1;
               }
        }
        update(activecon);
    }

    // execute any post-processing operations
    global void finish(Database.BatchableContext BC) {
    }
}