force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <description>Custom object used for connecting external TAM/TED database data with Leads and Contact data.</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Apex_last_updated_at__c.field-meta.xml
<CustomField>
    <fullName>Apex_last_updated_at__c</fullName>
    <description>Date for Apex OrgUpdateSweep scheduler</description>
    <label>Apex last updated at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Organization__c/fields/LOGIC_Apex_counter__c.field-meta.xml
<CustomField>
    <fullName>LOGIC_Apex_counter__c</fullName>
    <description>Field for Apex sweeper to update to trigger process builders</description>
    <label>LOGIC Apex counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrgUpdateSweepDesc.cls
global class OrgUpdateSweepDesc implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {

      String query = 'SELECT id, LOGIC_Apex_counter__c ' +
                     'FROM Organization__c ORDER BY Apex_last_updated_at__c DESC LIMIT 5000';

      //system.debug('>>> query ' + query);
      return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Organization__c> batchevent) {
    system.debug('>>> listBE ' + batchevent);

        // process each batch of records
        for(Organization__c o : batchevent){
            if(o.LOGIC_Apex_counter__c == null) {
               o.LOGIC_Apex_counter__c = 1;
            } else {
               o.LOGIC_Apex_counter__c = o.LOGIC_Apex_counter__c + 1;
            }
        }
        update(batchevent);
    }

    global void finish(Database.BatchableContext BC) {
    // execute any post-processing operations
    }
}